spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.197.134:3306/security_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  servlet:
    multipart.max-file-size: 10MB
    multipart.max-request-size: 100MB

server:
  port: 8080

springfox:
  documentation:
    enabled: true

mybatis:
  type-aliases-package: com.example.securitydemo.model
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

com:
  example:
    security:
      code:
        image:
          length: 6
          expireIn: 120
          width: 100
      #          url: /user,/user/*
      browser:
        loginPage: /sign-demo.html
        loginType: JSON
        rememberMeSeconds: 120
      social:
        filterProcessUrl: /qqLogin
        qq:
          appId: 101386962
          appSecret: 2a0f820407df400b84a854d054be8b6a
          providerId: callback.do  # nginx转发未配置
